"""
brecq_vm/qdrop_vm의 기본 metric vocabulary(configs/vocab_generic.txt) 생성 (09-28).

목표: 평가 vocabulary(COCO-80, LVIS-1203)와 **이름이 겹치지 않는** 구체 명사 집합.
metric C = E[w w^T]는 "배포 시 들어올 수 있는 임의 프롬프트의 분포"를 대변해야 하므로,
평가 이름을 넣으면 zero-shot 주장이 깨진다(그건 --vm-vocab lvis = oracle ablation으로 따로 잰다).

절차 (결정적, 난수 없음):
  1. WordNet 명사 synset 중 구체 사물 루트(artifact/animal/plant/food/natural_object/person 등)의
     하위(hyponym closure)만 후보로 둔다.
  2. synset마다 첫 lemma 하나만 이름으로 쓴다(같은 개념 중복 방지). 3단어 이하, 영문자/공백/하이픈만.
  3. 제외: synset의 **어떤 lemma든** COCO/LVIS 이름(괄호 설명 제거, 소문자, '_'->' ')과 같으면
     그 synset 전체를 뺀다. --lvis-ann을 주면 LVIS의 synonyms와 synset id까지 써서 더 엄격하게 뺀다.
  4. SemCor 빈도(lemma.count()) 합 내림차순으로 상위 --n개. 동률(특히 빈도 0인 대다수)은 이름의
     sha1 순서로 정렬한다 -- 이름순이면 빈도 0 구간이 'a'로 시작하는 단어로 채워지는 편향이 생긴다.

실행:
    pip install nltk && python -c "import nltk; nltk.download('wordnet')"
    python pipeline/build_generic_vocab.py --out configs/vocab_generic.txt --n 4000
    # 서버에서 LVIS json이 있으면(synonyms/synset까지 제외, 더 엄격):
    python pipeline/build_generic_vocab.py --lvis-ann <lvis_v1_minival.json> --out configs/vocab_generic_strict.txt
"""
import argparse, hashlib, json, os, re

import yaml

ROOTS = ["artifact.n.01", "animal.n.01", "plant.n.02", "food.n.01", "food.n.02",
         "natural_object.n.01", "person.n.01", "body_part.n.01", "vehicle.n.01"]
NAME_RE = re.compile(r"^[a-z][a-z \-]*[a-z]$")


def norm(name):
    name = re.sub(r"\(.*?\)", "", name)
    return " ".join(name.replace("_", " ").lower().split())


def dataset_names(which):
    """ultralytics cfg의 이름 목록(ultralytics를 import하지 않고 yaml만 읽는다 -- cv2 등 불필요)."""
    import importlib.util
    spec = importlib.util.find_spec("ultralytics")
    root = os.path.dirname(spec.origin)
    d = yaml.safe_load(open(os.path.join(root, "cfg", "datasets", f"{which}.yaml")))
    n = d["names"]
    return [n[i] for i in range(len(n))]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="configs/vocab_generic.txt")
    ap.add_argument("--n", type=int, default=4000)
    ap.add_argument("--lvis-ann", default=None)
    args = ap.parse_args()
    from nltk.corpus import wordnet as wn

    banned = {norm(x) for x in dataset_names("coco") + dataset_names("lvis")}
    banned_synsets = set()
    if args.lvis_ann:
        cats = json.load(open(args.lvis_ann))["categories"]
        for c in cats:
            banned |= {norm(s) for s in c.get("synonyms", [])} | {norm(c["name"])}
            if c.get("synset"):
                banned_synsets.add(c["synset"])

    cand = {}
    for r in ROOTS:
        root = wn.synset(r)
        for s in root.closure(lambda x: x.hyponyms() + x.instance_hyponyms()):
            cand[s.name()] = s
    rows = []
    n_banned = 0
    for sid, s in cand.items():
        if s.instance_hypernyms():                 # 고유명사(인물·지명 인스턴스) 제외
            continue
        lemmas = s.lemmas()
        if sid in banned_synsets or any(norm(l.name()) in banned for l in lemmas):
            n_banned += 1
            continue
        name = norm(lemmas[0].name())
        if not NAME_RE.match(name) or len(name.split()) > 3 or name in banned:
            continue
        rows.append((-sum(l.count() for l in lemmas), hashlib.sha1(name.encode()).hexdigest(), name))
    rows.sort()
    seen, out = set(), []
    for _, _, name in rows:
        if name not in seen:
            seen.add(name)
            out.append(name)
        if len(out) >= args.n:
            break
    with open(args.out, "w") as fh:
        fh.write(f"# generated by pipeline/build_generic_vocab.py (WordNet {wn.get_version()}, "
                 f"roots={','.join(ROOTS)}, n={len(out)}, lvis_ann={'yes' if args.lvis_ann else 'no'})\n")
        fh.write("# COCO-80/LVIS-1203 이름과 겹치는 synset 제외 -- 평가 vocabulary와 disjoint\n")
        fh.write("\n".join(out) + "\n")
    n_freq = sum(1 for r in rows if r[0] < 0)
    print(f"후보 synset {len(cand)}개, COCO/LVIS와 겹쳐 제외 {n_banned}개, 빈도>0 {n_freq}개, "
          f"기록 {len(out)}개 -> {args.out}")


if __name__ == "__main__":
    main()
